{% set name = "mupdf" %}
{% set version = "1.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://www.mupdf.com/downloads/archive/{{ name }}-{{ version }}-source.tar.gz
    sha256: ae2442416de499182d37a526c6fa2bacc7a3bed5a888d113ca04844484dfe7c6
    patches:
      # OSX has libfreetype.a, not libfreetype2.a
      - patches/Makerules.patch           # [osx]
      - patches/MakefileOSX.patch         # [osx]
      - patches/OSXSharedCreation.patch   # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msys2-sed        # [win]
    - msys2-make       # [win]
    - msys2-coreutils  # [win]
    - cmake            # [win]
    - ninja-base       # [win]
    - make             # [unix]
    - python
    - pkg-config
    # pyclang needed for library generation through Python scripts
    - python-clang
    - swig
  host:
    - python-clang
    - mujs
    - libgumbo
    - jbig2dec
    - brotli {{ brotli }}
    - xorg-libxfixes  # [unix]
    - libglu {{ libglu }}  # [linux]
    - mesalib {{ mesalib }}  # [linux]
    - freetype {{ freetype }}
    - libjpeg-turbo {{ libjpeg_turbo }}
    - libopenjpeg {{ libopenjpeg }}
    - zlib {{ zlib }}
    - libcurl {{ libcurl }}
    - harfbuzz {{ harfbuzz }}
    - freeglut {{ freeglut }}  # [linux or win]
  run:
    - mujs
    - openssl
    - libgumbo
    - xorg-libxext  # [unix]
    - xorg-libx11  # [unix]
    - curl

test:
  commands:
    - test -f $PREFIX/bin/mutool  # [unix]
    - test -f $PREFIX/lib/libmupdf${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\\mutool.exe exit 1  # [win]

about:
  home: https://www.mupdf.com
  license: AGPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A lightweight PDF, XPS, and E-book viewer
  description: |
    The renderer in MuPDF is tailored for high quality anti-aliased graphics.
    It renders text with metrics and spacing accurate to within fractions of
    a pixel for the highest fidelity in reproducing the look of a printed page
    on screen.
  doc_url: https://www.mupdf.com/docs
  dev_url: https://github.com/ArtifexSoftware/mupdf

extra:
  recipe-maintainers:
    - xmnlab
    - scopatz
    - jan-janssen